<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/NumPy-and-Pandas/DF_pandas_3_amaliyot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **1-mashq**. `Pandas` kutubxonasini `pd`, `numpy` kutubxonasini `np` deb chaqirib oling

In [1]:
# Javobni shuyerga yozing
import pandas as pd
import numpy as np

### Mashg'ulot uchun DF yuklab olamiz.
Quyidagi kodni bajaring

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

### **2-mashq.** DF hajmini chiqaring

In [3]:
# Javobni shuyerga yozing
df.shape

(2499, 12)

### **3-mashq**. DF boshidan 6 ta qator chiqaring

In [6]:
# Javobni shuyerga yozing
df.head(6)

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
5,5700,dodge,mpv,2018,clean vehicle,45561,white,2c4rdgeg9jr237989,167655771,texas,usa,2 days left

### **4-mashq.** DF oxiridan 5 ta qator chiqaring

In [7]:
# Javobni shuyerga yozing
df.tail()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

### **5-mashq**. DF ni yili `year` bo'yicha tartiblab chiqaring

In [9]:
# Javobni shuyerga yozing
df.sort_values(by = "year")

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
32,29800,chevrolet,camaro,1973,clean vehicle,46226,red,1q87t3n166389,167763370,pennsylvania,usa,22 hours left
405,25,ford,door,1984,salvage insurance,41577,white,2ftcf15y9eca14589,167611661,arkansas,usa,17 hours left
545,0,gmc,door,1993,salvage insurance,0,light blue,1gkfk16k5pj701631,167358601,colorado,usa,18 hours left
362,25,ford,pickup,1994,salvage insurance,206162,white,1ftdf15y2rnb12612,167361489,georgia,usa,2 days left
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
426,55600,lexus,gx,2020,clean vehicle,8186,silver,jtjam7bx4l5251250,167605747,florida,usa,2 days left
806,28300,chevrolet,colorado,2020,clean vehicle,13886,silver,1gcgtcen7l1101496,167805497,indiana,usa,2 days left
2322,15000,nissan,altima,2020,clean vehicle,14320,blue,1n4bl4cv4lc134145,167656212,ohio,usa,2 days left
2344,20100,nissan,rogue,2020,clean vehicle,10875,blue,jn8at2mvxlw103235,167614842,minnesota,usa,14 hours left
1388,17000,ford,fusion,2020,clean vehicle,1117,gray,3fa6p0d98lr194138,167742945,pennsylvania,usa,2 days left

### **6-mashq**. DF qatorlarini narxi bo'yicha reytinglang va konsolga narxi bo'yicha tartiblangan holatda chiqaring.

In [13]:
# Javobni shuyerga yozing
df['Rank'] = df['price'].rank()
df.sort_values('price')

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rank,Rank
410,0,chevrolet,door,1995,salvage insurance,274706,green,2gcec19h8s1195266,167425634,arizona,usa,2 days left,22.0,22.0
330,0,ford,door,1996,salvage insurance,296860,green,1falp62w5th144314,167359712,california,usa,19 hours left,22.0,22.0
331,0,ford,door,2006,salvage insurance,203158,red,1fmzk04136ga07119,167610991,illinois,usa,17 hours left,22.0,22.0
339,0,ford,door,2002,salvage insurance,214800,black,3fafp37372r151014,167360232,south carolina,usa,2 days left,22.0,22.0
496,0,ford,pickup,1996,salvage insurance,252588,red,1ftef15n0tlc14455,167357804,oklahoma,usa,17 hours left,22.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,65500,ford,srw,2019,clean vehicle,6500,black,1ft7w2bt0kec44818,167718954,indiana,usa,21 hours left,2495.0,2495.0
277,67000,dodge,challenger,2019,clean vehicle,10944,blue,2c3cdzl97kh518237,167759490,ohio,usa,21 hours left,2496.0,2496.0
1336,70000,ford,drw,2019,clean vehicle,9643,no_color,1ft8w3dt3kee48276,167780680,illinois,usa,2 days left,2497.0,2497.0
1340,74000,ford,drw,2019,clean vehicle,10536,no_color,1ft8w4dt6ked32656,167780682,illinois,usa,2 days left,2498.0,2498.0
502,84900,mercedes-benz,sl-class,2017,clean vehicle,25302,silver,wddjk7ea3hf044968,167607883,florida,usa,2 days left,2499.0,2499.0

### **7-mashq**. DFdan eng qimmat mashina haqidagi ma'lumotni chiqaring

In [15]:
# Javobni shuyerga yozing
df['price'].max()

84900

In [16]:
print("Umumiy ma'lumotlar")
idx = df['price'].idxmax()
df.iloc[idx]

Umumiy ma'lumotlar

price                         84900
brand                 mercedes-benz
model                      sl-class
year                           2017
title_status          clean vehicle
mileage                       25302
color                        silver
vin               wddjk7ea3hf044968
lot                       167607883
state                       florida
country                         usa
condition               2 days left
rank                         2499.0
Rank                         2499.0
Name: 502, dtype: object

### **8-mashq**. DFdan eng ko'p yurgan (`km_driven`) mashina haqidagi ma'lumotni chiqaring

In [21]:
# Javobni shuyerga yozing
km_driven = df["mileage"].idxmax()
df.iloc[km_driven]

price                          1025
brand                     peterbilt
model                         truck
year                           2010
title_status      salvage insurance
mileage                     1017936
color                        color:
vin               1xp7d49x0ad793710
lot                       167529842
state                       georgia
country                         usa
condition             17 hours left
rank                           94.5
Rank                           94.5
Name: 528, dtype: object

### **9-mashq**. DF dagi barcha brandlar va ularning sonini chiqaring

In [22]:
# Javobni shuyerga yozing
df["brand"].value_counts()

brand
ford               1235
dodge               432
nissan              312
chevrolet           297
gmc                  42
jeep                 30
chrysler             18
bmw                  17
hyundai              15
kia                  13
buick                13
infiniti             12
honda                12
cadillac             10
mercedes-benz        10
heartland             5
land                  4
peterbilt             4
audi                  4
acura                 3
lincoln               2
lexus                 2
mazda                 2
maserati              1
toyota                1
harley-davidson       1
jaguar                1
ram                   1
Name: count, dtype: int64

### **10-mashq**. DF dagi raqamli ustunlar haqida umulashtiruvchi statistikani chiqaring (min, max, mean, std va hokazo)

In [23]:
# Javobni shuyerga yozing
df.describe()

,price,year,mileage,lot,rank,Rank
count,2499.000000,2499.000000,2.499000e+03,2.499000e+03,2499.000000,2499.000000
mean,18767.671469,2016.714286,5.229869e+04,1.676914e+08,1250.000000,1250.000000
std,12116.094936,3.442656,5.970552e+04,2.038772e+05,721.537031,721.537031
min,0.000000,1973.000000,0.000000e+00,1.593488e+08,22.000000,22.000000
25%,10200.000000,2016.000000,2.146650e+04,1.676253e+08,623.500000,623.500000
50%,16900.000000,2018.000000,3.536500e+04,1.677451e+08,1251.500000,1251.500000
75%,25555.500000,2019.000000,6.347250e+04,1.677798e+08,1874.500000,1874.500000
max,84900.000000,2020.000000,1.017936e+06,1.678055e+08,2499.000000,2499.000000

### **11-mashq**. DF dan ford kompaniyasining barcha mashinalarnini ajratib chiqaring

In [25]:
# Javobni shuyerga yozing
df[ df["brand"] == "ford"]

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rank,Rank
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,156.0,156.0
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,1832.5,1832.5
9,5250,ford,mpv,2017,clean vehicle,63418,black,2fmpk3j92hbc12542,167656121,texas,usa,2 days left,323.0,323.0
14,20700,ford,door,2013,clean vehicle,100757,black,1ftfw1et7dfa47790,167753916,virginia,usa,22 hours left,1525.0,1525.0
18,5210,ford,mpv,2017,clean vehicle,35714,white,2fmpk3j95hbb73607,167656124,texas,usa,2 days left,322.0,322.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2199,13800,ford,fusion,2019,clean vehicle,29345,white,3fa6p0lu1kr222799,167802379,north carolina,usa,2 days left,911.5,911.5
2200,56000,ford,srw,2018,clean vehicle,25371,black,1ft7w2bt4jec50359,167749689,pennsylvania,usa,3 days left,2476.0,2476.0
2201,13800,ford,fusion,2019,clean vehicle,30054,silver,3fa6p0lu3kr210749,167802380,north carolina,usa,2 days left,911.5,911.5
2202,45800,ford,srw,2018,clean vehicle,11173,white,1ft7w2bt3jeb02932,167749690,pennsylvania,usa,2 days left,2405.0,2405.0
2203,13800,ford,fusion,2019,clean vehicle,30902,no_color,3fa6p0lu8kr225585,167802381,north carolina,usa,2 days left,911.5,911.5

### **12-mashq**. Nissan kompaniyasining eng qimmat va eng arzon mashinalarini chiqaring

In [27]:
# Javobni shuyerga yozing
df_nissan = df[df.brand =='nissan']
df_nissan.loc[df_nissan['price'].idxmin()]

price                           375
brand                        nissan
model                          door
year                           2017
title_status      salvage insurance
mileage                           1
color                           red
vin               3n1ce2cp0hl360793
lot                       167619908
state                north carolina
country                         usa
condition               2 days left
rank                           74.0
Rank                           74.0
Name: 2417, dtype: object

In [28]:
df_nissan = df[df.brand =='nissan']
df_nissan.loc[df_nissan['price'].idxmax()]

price                         36300
brand                        nissan
model                            xd
year                           2017
title_status          clean vehicle
mileage                       16224
color                         white
vin               1n6ba1f46hn535299
lot                       167753308
state                      virginia
country                         usa
condition             21 hours left
rank                         2305.5
Rank                         2305.5
Name: 2375, dtype: object

### **13-mashq**. Chevrolet kompaniyasining barcha modellarini chiqaring

In [30]:
# Javobni shuyerga yozing
df[df["brand"] == "chevrolet"]

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rank,Rank
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,2005.0,2005.0
6,7300,chevrolet,pk,2010,clean vehicle,149050,black,1gcsksea1az121133,167753872,georgia,usa,22 hours left,440.0,440.0
8,14600,chevrolet,malibu,2018,clean vehicle,9371,silver,1g1zd5st5jf191860,167763267,florida,usa,22 hours left,994.5,994.5
12,31900,chevrolet,1500,2018,clean vehicle,22909,black,3gcukrec0jg176059,167763273,tennessee,usa,22 hours left,2193.5,2193.5
22,15000,chevrolet,door,2015,clean vehicle,61578,black,2gnflhe33f6214023,167763280,ohio,usa,2 days left,1031.0,1031.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803,28300,chevrolet,ld,2019,clean vehicle,27665,red,2gcvkpec1k1124569,167805479,indiana,usa,2 days left,2036.5,2036.5
804,27300,chevrolet,ld,2019,clean vehicle,25427,black,2gcvkpec4k1105269,167805483,indiana,usa,2 days left,1988.0,1988.0
805,3500,chevrolet,door,2013,clean vehicle,78198,gray,1g11c5saxdf350889,167617243,new jersey,usa,7 days left,201.0,201.0
806,28300,chevrolet,colorado,2020,clean vehicle,13886,silver,1gcgtcen7l1101496,167805497,indiana,usa,2 days left,2036.5,2036.5
807,18300,chevrolet,impala,2019,clean vehicle,34538,silver,2g11z5s37k9134455,167805500,indiana,usa,2 days left,1362.0,1362.0

### **14-mashq**. Mashina narxi va yili o'rtasidagi korrelyasiya qiymatini chiqaring

In [34]:
# Javobni shuyerga yozing
df["price"].corr(df.year)

0.4182735684917942

### **14-mashq**. Mashina narxi va boshqa ustunlar o'rtasidagi korrelyasiyani chiqaring

In [42]:
# Javobni shuyerga yozing
df_for_corr = df.describe()
df_for_corr

,price,year,mileage,lot,rank,Rank
count,2499.000000,2499.000000,2.499000e+03,2.499000e+03,2499.000000,2499.000000
mean,18767.671469,2016.714286,5.229869e+04,1.676914e+08,1250.000000,1250.000000
std,12116.094936,3.442656,5.970552e+04,2.038772e+05,721.537031,721.537031
min,0.000000,1973.000000,0.000000e+00,1.593488e+08,22.000000,22.000000
25%,10200.000000,2016.000000,2.146650e+04,1.676253e+08,623.500000,623.500000
50%,16900.000000,2018.000000,3.536500e+04,1.677451e+08,1251.500000,1251.500000
75%,25555.500000,2019.000000,6.347250e+04,1.677798e+08,1874.500000,1874.500000
max,84900.000000,2020.000000,1.017936e+06,1.678055e+08,2499.000000,2499.000000

In [43]:
df_for_corr.corr()

            price      year   mileage       lot      rank      Rank
price    1.000000  0.074933  0.967568  0.336656  0.569857  0.569857
year     0.074933  1.000000  0.070671  0.465911  0.395613  0.395613
mileage  0.967568  0.070671  1.000000  0.231128  0.526921  0.526921
lot      0.336656  0.465911  0.231128  1.000000 -0.162819 -0.162819
rank     0.569857  0.395613  0.526921 -0.162819  1.000000  1.000000
Rank     0.569857  0.395613  0.526921 -0.162819  1.000000  1.000000

### **15-mashq**. DF dan kia va hyundai mashinalarini ajratib alohida DF ga saqlang. Yangi DFni chiqaring

In [ ]:
# Javobni shuyerga yozing
brands = ["kia", "hyundai"]
df2 = df[df["brand"]]

In [ ]:
#@title **To'g'ri javob**
brands = ['kia','hyundai']
df2 = df[df['brand'].isin(brands)]
df2

     price    brand     model  ...  country      condition    rank
16    5200      kia     forte  ...      usa    2 days left   319.0
21    7300      kia     forte  ...      usa    2 days left   440.0
26   21500      kia   sorento  ...      usa    2 days left  1566.5
287   8200  hyundai      door  ...      usa   5 hours left   506.5
288   3000      kia      door  ...      usa    9 days left   168.0
291  12700      kia      soul  ...      usa   10 days left   806.5
292  13800      kia   sorento  ...      usa    3 days left   911.5
296   9800  hyundai   elantra  ...      usa   5 hours left   605.0
366   5350  hyundai       mpv  ...      usa  22 hours left   326.5
389   3760  hyundai     doors  ...      usa  22 hours left   216.0
417   5998  hyundai     doors  ...      usa    5 days left   358.0
419      0      kia     wagon  ...      usa  16 hours left    22.0
424   3960  hyundai     doors  ...      usa    2 days left   232.5
438   4010  hyundai     doors  ...      usa    2 days left   240.0
440  13000      kia  sportage  ...      usa   2 hours left   841.5
450   4690  hyundai       mpv  ...      usa    2 days left   290.0
463   8000  hyundai      door  ...      usa    7 days left   493.5
486   4730  hyundai       mpv  ...      usa    2 days left   295.0
513   4650  hyundai       mpv  ...      usa    2 days left   289.0
525   3440  hyundai     doors  ...      usa    2 days left   192.5
527   3810      kia      door  ...      usa  20 hours left   222.0
537   4750  hyundai       mpv  ...      usa    2 days left   296.0
549   3460  hyundai      door  ...      usa    2 days left   197.0
551   3250  hyundai      door  ...      usa  20 hours left   185.5
623  14000      kia   sorento  ...      usa   5 hours left   949.0
626  13300      kia      door  ...      usa   5 hours left   862.5
629  15500      kia   sorento  ...      usa   5 hours left  1091.0
631  21500      kia   sorento  ...      usa   5 hours left  1566.5

[28 rows x 13 columns]

### **16-mashq**. Chevrolet kompaniyasining malibu va impala mashinalarini alohida DF ko'rinishida chiqaring

In [45]:
# Javobni shuyerga yozing
brands2 = ["malibu", "impala"]
df3 = df[df["model"].isin(brands2)]
df3

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rank,Rank
8,14600,chevrolet,malibu,2018,clean vehicle,9371,silver,1g1zd5st5jf191860,167763267,florida,usa,22 hours left,994.5,994.5
47,19000,chevrolet,malibu,2017,clean vehicle,18414,white,1g1zh5sx9hf118136,167763675,tennessee,usa,22 hours left,1419.5,1419.5
107,18003,chevrolet,malibu,2017,clean vehicle,19117,no_color,1g1zh5sx7hf141060,167765112,michigan,usa,17 hours left,1342.0,1342.0
204,6000,chevrolet,malibu,2018,clean vehicle,42090,gray,1g1zb5st8jf226848,167765944,texas,usa,21 hours left,362.5,362.5
266,17100,chevrolet,malibu,2019,clean vehicle,15780,white,1g1zd5st5kf112138,167767034,washington,usa,2 days left,1274.0,1274.0
278,18900,chevrolet,impala,2019,clean vehicle,27601,white,1g11z5s37ku129047,167767312,texas,usa,21 hours left,1410.5,1410.5
281,18300,chevrolet,impala,2019,clean vehicle,25809,black,2g11z5s33k9132248,167767315,texas,usa,21 hours left,1362.0,1362.0
569,13500,chevrolet,impala,2018,clean vehicle,53194,white,2g1105s3xj9121918,167773137,new jersey,usa,7 hours left,878.5,878.5
647,9000,chevrolet,malibu,2016,clean vehicle,67527,gray,1g1zj5su8gf337274,167780142,wisconsin,usa,21 hours left,554.5,554.5
677,13700,chevrolet,malibu,2019,clean vehicle,47282,silver,1g1zd5st4kf126371,167787112,oklahoma,usa,21 hours left,897.5,897.5
686,12300,chevrolet,malibu,2018,clean vehicle,53599,black,1g1zd5stxjf140841,167787955,oklahoma,usa,21 hours left,782.0,782.0
688,13600,chevrolet,malibu,2018,clean vehicle,36047,white,1g1zd5st5jf249837,167787964,oklahoma,usa,21 hours left,889.0,889.0
691,13000,chevrolet,malibu,2018,clean vehicle,41751,gray,1g1zd5st8jf242655,167787968,oklahoma,usa,21 hours left,841.5,841.5
731,25000,chevrolet,impala,2020,clean vehicle,18715,silver,1g1105s31lu100901,167796081,nevada,usa,6 hours left,1832.5,1832.5
740,13700,chevrolet,impala,2019,clean vehicle,14939,blue,2g11z5s30k9137729,167796203,nevada,usa,9 minutes,897.5,897.5
741,15900,chevrolet,malibu,2019,clean vehicle,22026,black,1g1zd5st0kf187281,167796205,nevada,usa,1 hours left,1145.0,1145.0
768,10200,chevrolet,malibu,2018,clean vehicle,45836,white,1g1zd5stxjf175198,167800168,texas,usa,2 days left,623.5,623.5
791,15200,chevrolet,impala,2019,clean vehicle,32248,red,1g11z5sa4ku113760,167801930,north carolina,usa,2 days left,1054.0,1054.0
792,15000,chevrolet,impala,2019,clean vehicle,36165,silver,1g11z5sa7ku117222,167801932,north carolina,usa,2 days left,1031.0,1031.0
793,15500,chevrolet,impala,2019,clean vehicle,29922,charcoal,2g11z5saxk9120208,167801934,north carolina,usa,2 days left,1091.0,1091.0
794,15700,chevrolet,impala,2019,clean vehicle,26848,silver,2g11z5sa5k9140950,167801935,north carolina,usa,2 days left,1118.0,1118.0
795,14800,chevrolet,impala,2019,clean vehicle,41163,charcoal,2g11z5sa8k9139310,167801936,north carolina,usa,2 days left,1011.5,1011.5
797,8200,chevrolet,impala,2017,clean vehicle,100315,black,1g1105sa9hu160835,167802211,north carolina,usa,2 days left,506.5,506.5
807,18300,chevrolet,impala,2019,clean vehicle,34538,silver,2g11z5s37k9134455,167805500,indiana,usa,2 days left,1362.0,1362.0

### **17-mashq**. Ford kompaniyasining mustang modelini alohioda DF ga ajrating

In [51]:
df_mustang = df[(df['brand']=='ford') & (df['model']=='mustang')]
df_mustang.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rank,Rank
632,25511,ford,mustang,2019,clean vehicle,11342,gray,1fatp8uh4k5177265,167763745,michigan,usa,19 hours left,1873.5,1873.5
1224,21900,ford,mustang,2018,clean vehicle,29748,red,1fatp8uh4j5166362,167773235,new jersey,usa,2 days left,1589.0,1589.0
1266,22000,ford,mustang,2018,clean vehicle,6248,red,1fa6p8th3j5135439,167778967,illinois,usa,2 days left,1598.5,1598.5
1267,38200,ford,mustang,2019,clean vehicle,878,green,1fa6p8k02k5503784,167732976,florida,usa,1 days left,2333.5,2333.5
1269,35000,ford,mustang,2018,clean vehicle,2042,blue,1fa6p8cf9j5131958,167778969,illinois,usa,21 hours left,2281.5,2281.5

### **18-mashq**. 2018-yildan keyin chiqqan Mustang mashinalirining o'rtacha narxini chiqaring

In [53]:
# Javobni shuyerga yozing
df_mustang[df_mustang['year'] >= 2018]['price'].mean()

24837.444444444445

### **19-mashq**. Mustang mashinalari haqida umumlashgan statistikani chiqaring

In [55]:
# Javobni shuyerga yozing
df[df["model"] == "mustang"].info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 632 to 2128
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         29 non-null     int64
 1   brand         29 non-null     object
 2   model         29 non-null     object
 3   year          29 non-null     int64
 4   title_status  29 non-null     object
 5   mileage       29 non-null     int64
 6   color         29 non-null     object
 7   vin           29 non-null     object
 8   lot           29 non-null     int64
 9   state         29 non-null     object
 10  country       29 non-null     object
 11  condition     29 non-null     object
 12  rank          29 non-null     float64
 13  Rank          29 non-null     float64
dtypes: float64(2), int64(4), object(8)
memory usage: 3.4+ KB

In [56]:
df[df["model"] == "mustang"].describe()

,price,year,mileage,lot,rank,Rank
count,29.000000,29.000000,29.000000,2.900000e+01,29.000000,29.000000
mean,25841.758621,2018.517241,21551.931034,1.677386e+08,1791.189655,1791.189655
std,7781.073538,0.784706,12153.315994,7.464566e+04,390.396191,390.396191
min,15500.000000,2016.000000,878.000000,1.675552e+08,1091.000000,1091.000000
25%,20500.000000,2018.000000,11342.000000,1.677355e+08,1515.500000,1515.500000
50%,22000.000000,2019.000000,25011.000000,1.677637e+08,1598.500000,1598.500000
75%,29800.000000,2019.000000,31561.000000,1.677824e+08,2111.000000,2111.000000
max,49000.000000,2020.000000,41147.000000,1.678018e+08,2439.500000,2439.500000

### **20-mashq**. Sotuvdagi ford mashinalarining aksari nechachni yilda ishlab chiqarilganini toping

In [57]:
# Javobni shuyerga yozing
df[df["brand"] == "ford"][["year"]].value_counts().idxmax()

(2019,)