<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/NumPy-and-Pandas/Ma'lumotlarga_ishlov_berish_Ma'lumotlarni_tayyorlash_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

**.groupby()orqali guruhlash**

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data.csv",
                 index_col = 0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [4]:
df.company.unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mitsubishi',
       'nissan', 'porsche', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [5]:
df[df.company == "toyota"]

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

In [6]:
df.company.value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

In [7]:
# .yuqoridagi kodni filterlashning .groupby orqali bajarish
df.groupby("company").max()

,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
company,,,,,,,,
alfa-romero,hatchback,94.5,171.2,ohcv,six,154,21,16500.0
audi,wagon,105.8,192.7,ohc,four,115,24,18920.0
bmw,sedan,110.0,197.0,ohc,six,182,23,41315.0
chevrolet,sedan,94.5,158.8,ohc,three,70,47,6575.0
dodge,hatchback,93.7,157.3,ohc,four,68,31,6377.0
honda,wagon,96.5,175.4,ohc,four,101,30,12945.0
isuzu,sedan,94.5,170.7,ohc,four,78,38,6785.0
jaguar,sedan,113.0,199.6,ohcv,twelve,262,15,36000.0
mazda,sedan,104.9,175.0,rotor,two,101,31,18344.0
mercedes-benz,wagon,120.9,208.1,ohcv,five,184,22,45400.0
mitsubishi,sedan,96.3,172.4,ohc,four,88,37,8189.0
nissan,wagon,100.4,184.6,ohcv,six,152,45,13499.0
porsche,hatchback,98.4,175.7,ohcf,six,288,17,37028.0
toyota,wagon,104.5,187.8,ohc,six,156,35,15750.0
volkswagen,sedan,97.3,171.7,ohc,four,100,37,9995.0
volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [8]:
df.groupby("company").min()

,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
company,,,,,,,,
alfa-romero,convertible,88.6,168.8,dohc,four,111,19,13495.0
audi,sedan,99.4,176.6,ohc,five,102,18,13950.0
bmw,sedan,101.2,176.8,ohc,four,101,15,16430.0
chevrolet,hatchback,88.4,141.1,l,four,48,38,5151.0
dodge,hatchback,93.7,157.3,ohc,four,68,31,6229.0
honda,sedan,96.5,157.1,ohc,four,76,24,7295.0
isuzu,sedan,94.3,155.9,ohc,four,70,24,6785.0
jaguar,sedan,102.0,191.7,dohc,six,176,13,32250.0
mazda,hatchback,93.1,159.1,ohc,four,68,17,5195.0
mercedes-benz,hardtop,110.0,190.9,ohc,eight,123,14,25552.0
mitsubishi,hatchback,93.7,157.3,ohc,four,68,25,5389.0
nissan,sedan,94.5,165.3,ohc,four,55,19,6649.0
porsche,convertible,89.5,168.9,dohcv,eight,207,17,34028.0
toyota,hatchback,95.7,158.7,dohc,four,62,19,5348.0
volkswagen,sedan,97.3,171.7,ohc,four,52,26,7775.0
volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0

In [9]:
# endi ustunlarning bizga keraklisini olib natijalarni analiz qilishimiz mumkin
df.groupby("company").price.mean()

company
alfa-romero      15498.333333
audi             16392.500000
bmw              27213.333333
chevrolet         6007.000000
dodge             6303.000000
honda            10195.000000
isuzu             6785.000000
jaguar           34600.000000
mazda             9654.800000
mercedes-benz    35040.000000
mitsubishi        6689.000000
nissan            8289.000000
porsche          35528.000000
toyota            8216.857143
volkswagen        8435.000000
volvo            13177.500000
Name: price, dtype: float64

In [10]:
df.groupby("company").price.max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [11]:
df.groupby("company").price.sum()

company
alfa-romero       46495.0
audi              65570.0
bmw              163280.0
chevrolet         18021.0
dodge             12606.0
honda             30585.0
isuzu              6785.0
jaguar           103800.0
mazda             48274.0
mercedes-benz    140160.0
mitsubishi        26756.0
nissan            41445.0
porsche           71056.0
toyota            57518.0
volkswagen        33740.0
volvo             26355.0
Name: price, dtype: float64

In [12]:
# bitta emas ikki va undan ortiq guruhga ajratishimiz mumkin
df.groupby(["company", "engine-type"]).price.mean()

company        engine-type
alfa-romero    dohc           14997.500000
               ohcv           16500.000000
audi           ohc            16392.500000
bmw            ohc            27213.333333
chevrolet      l               5151.000000
               ohc             6435.000000
dodge          ohc             6303.000000
honda          ohc            10195.000000
isuzu          ohc             6785.000000
jaguar         dohc           33900.000000
               ohcv           36000.000000
mazda          ohc             9107.250000
               rotor          11845.000000
mercedes-benz  ohc            26900.000000
               ohcv           43180.000000
mitsubishi     ohc             6689.000000
nissan         ohc             6986.500000
               ohcv           13499.000000
porsche        dohcv                   NaN
               ohcf           35528.000000
toyota         dohc           15750.000000
               ohc             6961.333333
volkswagen     ohc             8435.000000
volvo          ohc            13177.500000
Name: price, dtype: float64

In [13]:
df.groupby(["company", "engine-type"]).max()

                            body-style  wheel-base  length num-of-cylinders  \
company       engine-type
alfa-romero   dohc         convertible        88.6   168.8             four
              ohcv           hatchback        94.5   171.2              six
audi          ohc                wagon       105.8   192.7             four
bmw           ohc                sedan       110.0   197.0              six
chevrolet     l              hatchback        88.4   141.1            three
              ohc                sedan        94.5   158.8             four
dodge         ohc            hatchback        93.7   157.3             four
honda         ohc                wagon        96.5   175.4             four
isuzu         ohc                sedan        94.5   170.7             four
jaguar        dohc               sedan       113.0   199.6              six
              ohcv               sedan       102.0   191.7           twelve
mazda         ohc                sedan       104.9   175.0             four
              rotor          hatchback        95.3   169.0              two
mercedes-benz ohc                wagon       110.0   190.9             five
              ohcv               sedan       120.9   208.1            eight
mitsubishi    ohc                sedan        96.3   172.4             four
nissan        ohc                wagon        94.5   170.2             four
              ohcv               sedan       100.4   184.6              six
porsche       dohcv          hatchback        98.4   175.7            eight
              ohcf             hardtop        89.5   168.9              six
toyota        dohc               wagon       104.5   187.8              six
              ohc                wagon        95.7   169.7             four
volkswagen    ohc                sedan        97.3   171.7             four
volvo         ohc                wagon       104.3   188.8             four

                           horsepower  average-mileage    price
company       engine-type
alfa-romero   dohc                111               21  16500.0
              ohcv                154               19  16500.0
audi          ohc                 115               24  18920.0
bmw           ohc                 182               23  41315.0
chevrolet     l                    48               47   5151.0
              ohc                  70               38   6575.0
dodge         ohc                  68               31   6377.0
honda         ohc                 101               30  12945.0
isuzu         ohc                  78               38   6785.0
jaguar        dohc                176               15  35550.0
              ohcv                262               13  36000.0
mazda         ohc                  72               31  18344.0
              rotor               101               17  11845.0
mercedes-benz ohc                 123               22  28248.0
              ohcv                184               14  45400.0
mitsubishi    ohc                  88               37   8189.0
nissan        ohc                  69               45   7349.0
              ohcv                152               19  13499.0
porsche       dohcv               288               17      NaN
              ohcf                207               17  37028.0
toyota        dohc                156               19  15750.0
              ohc                  62               35   8778.0
volkswagen    ohc                 100               37   9995.0
volvo         ohc                 114               23  13415.0

In [14]:
# bir guruh orqali bir nechta funksiyalarni qo'llash
df.groupby("company").agg([min, max])

<ipython-input-14-c723e6306329>:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby("company").agg([min, max])
<ipython-input-14-c723e6306329>:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby("company").agg([min, max])
<ipython-input-14-c723e6306329>:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby("company").agg([min, max])

                body-style            wheel-base        length         \
                       min        max        min    max    min    max
company
alfa-romero    convertible  hatchback       88.6   94.5  168.8  171.2
audi                 sedan      wagon       99.4  105.8  176.6  192.7
bmw                  sedan      sedan      101.2  110.0  176.8  197.0
chevrolet        hatchback      sedan       88.4   94.5  141.1  158.8
dodge            hatchback  hatchback       93.7   93.7  157.3  157.3
honda                sedan      wagon       96.5   96.5  157.1  175.4
isuzu                sedan      sedan       94.3   94.5  155.9  170.7
jaguar               sedan      sedan      102.0  113.0  191.7  199.6
mazda            hatchback      sedan       93.1  104.9  159.1  175.0
mercedes-benz      hardtop      wagon      110.0  120.9  190.9  208.1
mitsubishi       hatchback      sedan       93.7   96.3  157.3  172.4
nissan               sedan      wagon       94.5  100.4  165.3  184.6
porsche        convertible  hatchback       89.5   98.4  168.9  175.7
toyota           hatchback      wagon       95.7  104.5  158.7  187.8
volkswagen           sedan      sedan       97.3   97.3  171.7  171.7
volvo                sedan      wagon      104.3  104.3  188.8  188.8

              engine-type        num-of-cylinders         horsepower       \
                      min    max              min     max        min  max
company
alfa-romero          dohc   ohcv             four     six        111  154
audi                  ohc    ohc             five    four        102  115
bmw                   ohc    ohc             four     six        101  182
chevrolet               l    ohc             four   three         48   70
dodge                 ohc    ohc             four    four         68   68
honda                 ohc    ohc             four    four         76  101
isuzu                 ohc    ohc             four    four         70   78
jaguar               dohc   ohcv              six  twelve        176  262
mazda                 ohc  rotor             four     two         68  101
mercedes-benz         ohc   ohcv            eight    five        123  184
mitsubishi            ohc    ohc             four    four         68   88
nissan                ohc   ohcv             four     six         55  152
porsche             dohcv   ohcf            eight     six        207  288
toyota               dohc    ohc             four     six         62  156
volkswagen            ohc    ohc             four    four         52  100
volvo                 ohc    ohc             four    four        114  114

              average-mileage        price
                          min max      min      max
company
alfa-romero                19  21  13495.0  16500.0
audi                       18  24  13950.0  18920.0
bmw                        15  23  16430.0  41315.0
chevrolet                  38  47   5151.0   6575.0
dodge                      31  31   6229.0   6377.0
honda                      24  30   7295.0  12945.0
isuzu                      24  38   6785.0   6785.0
jaguar                     13  15  32250.0  36000.0
mazda                      17  31   5195.0  18344.0
mercedes-benz              14  22  25552.0  45400.0
mitsubishi                 25  37   5389.0   8189.0
nissan                     19  45   6649.0  13499.0
porsche                    17  17  34028.0  37028.0
toyota                     19  35   5348.0  15750.0
volkswagen                 26  37   7775.0   9995.0
volvo                      23  23  12940.0  13415.0

In [15]:
# faqat bitta ustun orqali chiqarish
df.groupby("company").price.agg([min, max, np.median])

<ipython-input-15-173157d9ab2e>:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby("company").price.agg([min, max, np.median])
<ipython-input-15-173157d9ab2e>:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby("company").price.agg([min, max, np.median])
<ipython-input-15-173157d9ab2e>:2: FutureWarning: The provided callable <function median at 0x7f4f4dc14ca0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby("company").price.agg([min, max, np.median])

                   min      max   median
company
alfa-romero    13495.0  16500.0  16500.0
audi           13950.0  18920.0  16350.0
bmw            16430.0  41315.0  25865.0
chevrolet       5151.0   6575.0   6295.0
dodge           6229.0   6377.0   6303.0
honda           7295.0  12945.0  10345.0
isuzu           6785.0   6785.0   6785.0
jaguar         32250.0  36000.0  35550.0
mazda           5195.0  18344.0   6795.0
mercedes-benz  25552.0  45400.0  34604.0
mitsubishi      5389.0   8189.0   6589.0
nissan          6649.0  13499.0   7099.0
porsche        34028.0  37028.0  35528.0
toyota          5348.0  15750.0   6918.0
volkswagen      7775.0   9995.0   7985.0
volvo          12940.0  13415.0  13177.5

In [16]:
df.groupby("body-style").price.agg([len, min, max])

<ipython-input-16-7acd55ceae08>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby("body-style").price.agg([len, min, max])
<ipython-input-16-7acd55ceae08>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby("body-style").price.agg([len, min, max])

             len      min      max
body-style
convertible    3  13495.0  37028.0
hardtop        2  34028.0  45400.0
hatchback     15   5151.0  16500.0
sedan         32   6575.0  41315.0
wagon          9   6918.0  28248.0

In [17]:
df.groupby("body-style").agg([len, min, max])

<ipython-input-17-c8b82ae5c4a2>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby("body-style").agg([len, min, max])
<ipython-input-17-c8b82ae5c4a2>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby("body-style").agg([len, min, max])

            company                         wheel-base              length  \
                len            min      max        len   min    max    len
body-style
convertible       3    alfa-romero  porsche          3  88.6   89.5      3
hardtop           2  mercedes-benz  porsche          2  89.5  112.0      2
hatchback        15    alfa-romero   toyota         15  88.4   98.4     15
sedan            32           audi    volvo         32  94.3  120.9     32
wagon             9           audi    volvo          9  94.5  110.0      9

                          engine-type  ... num-of-cylinders horsepower       \
               min    max         len  ...              max        len  min
body-style                             ...
convertible  168.8  168.9           3  ...              six          3  111
hardtop      168.9  199.2           2  ...              six          2  184
hatchback    141.1  175.7          15  ...              two         15   48
sedan        155.9  208.1          32  ...           twelve         32   52
wagon        157.1  192.7           9  ...              six          9   62

                 average-mileage         price
             max             len min max   len      min      max
body-style
convertible  207               3  17  21     3  13495.0  37028.0
hardtop      207               2  14  17     2  34028.0  45400.0
hatchback    288              15  17  47    15   5151.0  16500.0
sedan        262              32  13  45    32   6575.0  41315.0
wagon        156               9  19  31     9   6918.0  28248.0

[5 rows x 24 columns]

**Gʻayritabiiy qiymatlar bilan ishlash**

In [18]:
df2 = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/MOCK_USER_DATA.csv",
                  index_col = 0)
df2.head()

   first_name   last_name                           email       gender   age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3      Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48

In [19]:
# df da g'ayritabiiy elementlar ham bor va buni tozalab olishimiz kerak
df2.describe()

               age
count   100.000000
mean    145.660000
std     565.631411
min     -85.000000
25%      22.750000
50%      53.500000
75%      84.250000
max    4444.000000

In [20]:
df2.shape

(100, 5)

In [21]:
# yosh (age) ning g'alati bo'lganlarni ajratib ko'rishimiz mumkin
# inson max yoshi 123 bo'lishi mumkin
df2[df2.age > 123]

    first_name  last_name                           email       gender   age
id
3       Lilith   Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
39      Godard      Miere               gmiere12@1688.com   Polygender  3434
47       Cleve  Sparshatt      csparshatt1a@economist.com  Genderfluid   333
49       Trace   Stockney          tstockney1c@flavors.me       Female   344
65      Eloise    Snoddon    esnoddon1s@elegantthemes.com  Genderfluid   332
80       Gabie     Rothon              grothon27@ehow.com  Genderqueer  4444
100      Mable    Toffano          mtoffano2r@myspace.com     Bigender   233

In [22]:
df2[df2.age < 0]

   first_name  last_name                           email       gender  age
id
11     Elijah      Heine                eheinea@imdb.com     Bigender  -85
19      Luisa  Bradborne            lbradbornei@fema.gov       Female  -75
21      Levin     Worner                lwornerk@ihg.com  Genderqueer  -43
33   Ebenezer    Greeves           egreevesw@myspace.com         Male  -26
38       Hana   Langwade  hlangwade11@washingtonpost.com  Genderqueer  -42
90  Zachariah      Meins            zmeins2h@weather.com         Male  -69

In [23]:
# | bu belgi yoki (or) ni beradi
df2[(df2.age > 123) | (df2.age < 0)]

    first_name  last_name                           email       gender   age
id
3       Lilith   Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
11      Elijah      Heine                eheinea@imdb.com     Bigender   -85
19       Luisa  Bradborne            lbradbornei@fema.gov       Female   -75
21       Levin     Worner                lwornerk@ihg.com  Genderqueer   -43
33    Ebenezer    Greeves           egreevesw@myspace.com         Male   -26
38        Hana   Langwade  hlangwade11@washingtonpost.com  Genderqueer   -42
39      Godard      Miere               gmiere12@1688.com   Polygender  3434
47       Cleve  Sparshatt      csparshatt1a@economist.com  Genderfluid   333
49       Trace   Stockney          tstockney1c@flavors.me       Female   344
65      Eloise    Snoddon    esnoddon1s@elegantthemes.com  Genderfluid   332
80       Gabie     Rothon              grothon27@ehow.com  Genderqueer  4444
90   Zachariah      Meins            zmeins2h@weather.com         Male   -69
100      Mable    Toffano          mtoffano2r@myspace.com     Bigender   233

In [24]:
# endi yuqoridagi g'alati elementlar bilan ishlash uchun apply metodi kerak
# apply ichidagi funksiyani ishlaydi
# abs qiymat manfiyni musbat qilib beradi
df2.age = df2.age.apply(np.abs)
df3

NameError: name 'df3' is not defined

In [ ]:
# endi esa 123 yshdan katta rowslarni o'chirib tashashimiz keral
idx = df2[df2.age > 123].index
idx
df2.drop(index = idx, inplace = True)

In [25]:
# endi qiymatlar juda yaxshi ko'rinishga keldi
df2.describe()

               age
count   100.000000
mean    152.460000
std     563.818411
min       1.000000
25%      32.000000
50%      59.000000
75%      85.000000
max    4444.000000

In [26]:
df2

    first_name   last_name                           email       gender   age
id
1      Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2      Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3       Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4         Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5     Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48
..         ...         ...                             ...          ...   ...
96        Baxy       Marcu        bmarcu2n@list-manage.com      Agender    64
97      Kattie     Claxson          kclaxson2o@booking.com       Female    18
98        Clem     Fullerd  cfullerd2p@creativecommons.org     Bigender    55
99   Desdemona     Jurasek        djurasek2q@aboutads.info  Genderfluid    46
100      Mable     Toffano          mtoffano2r@myspace.com     Bigender   233

[100 rows x 5 columns]

In [27]:
df2.gender.value_counts()

gender
Male           21
Genderfluid    14
Bigender       13
Female         12
Genderqueer    11
Non-binary     10
Polygender     10
Agender         9
Name: count, dtype: int64

In [28]:
# bizga gender ichida male va female kerak
df2_gender = df2[df2.gender.isin(["Male", "Female"])]
df2_gender

   first_name     last_name                         email  gender  age
id
2     Pietrek       Scanlin        pscanlin1@yolasite.com    Male   91
5    Mohammed    Habbershon  mhabbershon4@sourceforge.net  Female   48
10      David      Meredyth    dmeredyth9@telegraph.co.uk  Female   68
12  Raffaello     Firminger     rfirmingerb@bloomberg.com  Female   74
17      Byram   Martynikhin     bmartynikhing@jiathis.com    Male   40
19      Luisa     Bradborne          lbradbornei@fema.gov  Female   75
22        Ray         Padly           rpadlyl@twitpic.com    Male   85
26   Ephrayim    Westmacott         ewestmacottp@ning.com    Male   77
29      Biron      Acklands        backlandss@comsenz.com    Male   13
33   Ebenezer       Greeves         egreevesw@myspace.com    Male   26
34     Brooks          Vose             bvosex@amazon.com  Female   34
36        Axe       Arundel           aarundelz@yahoo.com  Female   14
43       Bili     Swetenham        bswetenham16@europa.eu    Male   23
46     Alvira  Stollsteiner     astollsteiner19@mysql.com    Male   66
49      Trace      Stockney        tstockney1c@flavors.me  Female  344
58     Brynna        Worsom              bworsom1l@wp.com    Male   66
61       Page       Merrell     pmerrell1o@slideshare.net    Male    1
62     Kennan         Visco          kvisco1p@jiathis.com  Female   94
63   Adrianne       Gommowe  agommowe1q@deliciousdays.com    Male  100
67     Bunnie        Ozanne      bozanne1u@whitehouse.gov    Male   92
70      Ambur        Aickin           aaickin1x@about.com    Male   60
72   Eleanora       Kamenar       ekamenar1z@examiner.com    Male   47
74      Curry    Smalecombe  csmalecombe21@washington.edu    Male   69
76      Misty         Blanc         mblanc23@amazon.co.jp    Male   74
77     Rudolf        Kalewe           rkalewe24@fotki.com    Male   12
81       Alex         Darth    adarth28@ezinearticles.com  Female   98
86    Rogerio          Akid           rakid2d@latimes.com  Female    3
87      Peder        Murrie       pmurrie2e@bloglovin.com    Male   69
88       Kain     Dumphries  kdumphries2f@hugedomains.com    Male   93
90  Zachariah         Meins          zmeins2h@weather.com    Male   69
91      Judas        Maffin         jmaffin2i@dropbox.com    Male    3
94     Sheree        Cockin     scockin2l@accuweather.com  Female   94
97     Kattie       Claxson        kclaxson2o@booking.com  Female   18

**Jadvaldan tasodifiy qiymatlarni olish**

In [29]:
df3 = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/MOCK_USER_DATA.csv",
                  index_col = 0)
df3.head()

   first_name   last_name                           email       gender   age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3      Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48

In [30]:
len(df3)

100

In [31]:
# biz ayrim vaqtda tartibli turgan narsalarni aralashtirib yuborishimiz kerak bo'ladi
# jadvalimiz 100 ta bo'lgani uchun 100 yozamiz
# permutation bu aralashtirib yuboradi
random_list = np.random.permutation(100)
random_list

array([26,  1, 47, 70, 12, 48, 21, 88, 82,  3, 64, 93,  9, 94, 22, 59, 86,
       84,  6, 79, 51, 37, 24, 18, 69, 20, 39, 96, 19, 57, 98, 55, 67, 36,
       49, 58, 74, 89, 91, 61, 30, 46, 38, 50, 10, 85, 28, 75, 78, 35, 80,
       73, 17, 29, 41, 33,  8, 53, 54, 42, 44, 99, 97, 56, 25, 95, 81, 62,
       90, 16, 68, 13, 60, 71, 92, 87, 45, 23, 76, 66, 72, 40, 52, 32, 34,
       11,  4,  5,  0,  7, 77,  2, 31, 27, 14, 43, 83, 65, 63, 15])

In [32]:
# yuqoridagi tasodifiy indexlar orqali joylashtirish kerak bo'lsa
df3.take(random_list)

   first_name   last_name                       email       gender  age
id
27    Natalee     Baudone      nbaudoneq@marriott.com  Genderqueer   74
2     Pietrek     Scanlin      pscanlin1@yolasite.com         Male   91
48  Sutherlan      Duigan           sduigan1b@ask.com   Non-binary   27
71       Zane    Brickham  zbrickham1y@soundcloud.com  Genderqueer    5
13    Kristan     Abriani          kabrianic@phoca.cz   Polygender   29
..        ...         ...                         ...          ...  ...
44     Marice   Champneys  mchampneys17@bigcartel.com     Bigender   49
84      Tildi    Phythien      tphythien2b@ustream.tv  Genderfluid   76
66     Alejoa  Abrahamoff       aabrahamoff1t@com.com   Polygender   28
64      Carla      Rumney         crumney1r@weibo.com   Polygender   56
16       Anny      Rodway       arodwayf@examiner.com   Non-binary   87

[100 rows x 5 columns]

In [34]:
# tasodifiy bo'lgan 10 ta takrorlanmas element
df3.sample(10)

    first_name   last_name                       email       gender  age
id
100      Mable     Toffano      mtoffano2r@myspace.com     Bigender  233
77      Rudolf      Kalewe         rkalewe24@fotki.com         Male   12
37      Daisie        Self         dself10@addthis.com      Agender   33
45     Koralle   Pumphreys      kpumphreys18@issuu.com   Polygender   38
54     Gregory       Criag     gcriag1h@purevolume.com   Polygender   50
70       Ambur      Aickin         aaickin1x@about.com         Male   60
26    Ephrayim  Westmacott       ewestmacottp@ning.com         Male   77
81        Alex       Darth  adarth28@ezinearticles.com       Female   98
67      Bunnie      Ozanne    bozanne1u@whitehouse.gov         Male   92
7        Wendy     Popland            wpopland6@cbc.ca  Genderfluid   67

In [36]:
# takrorlanuvchi 10 ta tasodifiy element
df3.sample(10, replace = True)

   first_name     last_name                           email       gender  age
id
87      Peder        Murrie         pmurrie2e@bloglovin.com         Male   69
18    Artemus      Shovelin           ashovelinh@sphinn.com   Non-binary   58
47      Cleve     Sparshatt      csparshatt1a@economist.com  Genderfluid  333
46     Alvira  Stollsteiner       astollsteiner19@mysql.com         Male   66
81       Alex         Darth      adarth28@ezinearticles.com       Female   98
84      Tildi      Phythien          tphythien2b@ustream.tv  Genderfluid   76
38       Hana      Langwade  hlangwade11@washingtonpost.com  Genderqueer  -42
40      Moria       Boullin         mboullin13@illinois.edu      Agender    8
46     Alvira  Stollsteiner       astollsteiner19@mysql.com         Male   66
11     Elijah         Heine                eheinea@imdb.com     Bigender  -85