<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/NumPy-and-Pandas/Ma'lumotlarga_ishlov_berish_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
# fayllar ketma-ketligida ochilishi
df = pd.read_csv("sample_data/california_housing_test.csv")
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

In [3]:
df.shape

(3000, 9)

In [8]:
df1 = pd.read_excel("uzbekistan.xlsx")
df1

In [ ]:
# index_col = 0 orqali, 0 o'rinda turgan columnni indexga o'zgartirdik. va names orqali nomlarini ham o'zgartirdik
df1 = pd.read_excel("uzbekistan.xlsx", index_col = 0, names = ["Hudud", "Maydon", "Aholi"])
df1

In [ ]:
df2 = pd.read_csv("automobile_data.csv", sep = ";")
df2

In [ ]:
# indexini companyga o'zgartirdik, nrows = df2.head(10)
df2 = pd.read_csv("automobile_data.csv", index_col = "company", nrows = 10)
df2

In [ ]:
df3 = pd.read_excel("uzbekistan.xlsx", index_col = 0, names = ["Hudud", "Maydon", "Aholi"])
df3

In [ ]:
# boshqa turdagi df ni, turi hamda qayta nomlash uchun ishlatiladi
# bu "to" orqali amalga oshiriladi
df3 = pd.read_excel("uzbekistan.xlsx", index_col = 0, names = ["Hudud", "Maydon", "Aholi"])
df3.to_csv("newuzbekistan.csv")

In [8]:
# index saqlanmaydi xotira uchun index_col = False uchun
df3 = pd.read_csv("newuzbekistan.csv", index_col = False)
df3

In [8]:
# index saqlanmaydi xotira uchun index_col = False uchun
df3 = pd.read_csv("newuzbekistan.csv", index_col = False)
df3# tools/node/ papkasiga saqlandi
df3 = pd.read_excel("uzbekistan.xlsx", index_col = 0, names = ["Hudud", "Maydon", "Aholi"])
df3.to_csv("tools/node/newuzbekistan.csv")

In [7]:
# index saqlanmaydi xotira uchun index_col = False uchun
df3 = pd.read_csv("newuzbekistan.csv", index_col = False)
df3# tools/node/ papkasiga saqlandi
df3 = pd.read_excel("uzbekistan.xlsx", index_col = 0, names = ["Hudud", "Maydon", "Aholi"])
df3.to_csv("tools/node/newuzbekistan.csv")# data.h5 formatidagi HDF Storega saqladik, hdfobj nom ostida dataframe
hdfobj = pd.HDFStore("data.h5")

In [8]:
# put orqali df2 ma'lumotlari hdfobj uchun saqlandi
hdfobj.put("uzdata", df2)

In [ ]:
# put orqali df3 ma'lumotlari hdfobj uchun saqlandi
hdfobj.put("cardata", df3)

In [34]:
# hdfobj ning kiritilgan kalitlarini ko'rish uchun
hdfobj.keys()

['/cardata', '/uzdata']

In [42]:
# kalit orqali ochish datani
hdfobj["uzdata"]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [39]:
# hdfobj file yopiladi
# ochish uchun esa hdfobj = pd.HDFStore("data.h5") ni qaytadan kiritamiz
hdfobj.close()

In [43]:
# qayta ochildi
hdfobj = pd.HDFStore("data.h5")

In [45]:
# web-sahifadan ko'chirib olish faqat jadvallarni oladi
tashkent = pd.read_html("http://en.wikipedia.org/wiki/Tashkent")

In [46]:
# dataframe ning jadvallar soni ko'rsatadi
len(tashkent)

18

In [48]:
# 5-jadvalni ochib beradi
tashkent[5]

   Climate data for Tashkent (1991–2020, extremes 1867–present)  \
                                                          Month
0                                 Record high °C (°F)
1                          Mean daily maximum °C (°F)
2                                  Daily mean °C (°F)
3                          Mean daily minimum °C (°F)
4                                  Record low °C (°F)
5                   Average precipitation mm (inches)
6              Average extreme snow depth cm (inches)
7                                  Average rainy days
8                                  Average snowy days
9                       Average relative humidity (%)
10                        Mean monthly sunshine hours
11                        Source 1: Pogoda.ru.net[54]
12                                 Source 2: NOAA[55]

                                                              \
                            Jan                          Feb
0                   22.6 (72.7)                  27.0 (80.6)
1                    7.2 (45.0)                   9.5 (49.1)
2                    2.3 (36.1)                   4.2 (39.6)
3                   −1.3 (29.7)                   0.1 (32.2)
4                     −28 (−18)                −25.6 (−14.1)
5                      55 (2.2)                     72 (2.8)
6                       3 (1.2)                      2 (0.8)
7                            14                           13
8                             9                            7
9                            73                           68
10                        104.7                        119.4
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            Mar                          Apr
0                   32.5 (90.5)                  36.4 (97.5)
1                   16.0 (60.8)                  22.3 (72.1)
2                   10.2 (50.4)                  15.9 (60.6)
3                    5.3 (41.5)                  10.1 (50.2)
4                   −16.9 (1.6)                  −6.3 (20.7)
5                      66 (2.6)                     63 (2.5)
6                         0 (0)                        0 (0)
7                            14                           12
8                             2                            0
9                            61                           60
10                        169.2                        222.7
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            May                          Jun
0                  39.9 (103.8)                 43.0 (109.4)
1                   28.0 (82.4)                  33.6 (92.5)
2                   21.1 (70.0)                  26.2 (79.2)
3                   14.3 (57.7)                  18.4 (65.1)
4                   −1.7 (28.9)                   3.8 (38.8)
5                      41 (1.6)                     17 (0.7)
6                         0 (0)                        0 (0)
7                            11                            7
8                             0                            0
9                            53                           40
10                        303.0                        352.8
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            Jul                          Aug
0                  44.6 (112.3)                 43.1 (109.6)
1                   35.9 (96.6)                  34.9 (94.8)
2                   28.3 (82.9)                  26.6 (79.9)
3                   20.1 (68.2)                  18.4 (65.1)
4                    8.2 (46.8)                   5.7 (42.3)
5                       3 (0.1)                      2 (0.1)
6                         0 (0)                        0 (0)
7                             4                            3
8                             0                            0
9                            39                           42
10                        386.5                        353.4
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            Sep                          Oct
0                  40.0 (104.0)                  37.5 (99.5)
1                   29.5 (85.1)                  22.2 (72.0)
2                   21.0 (69.8)                  14.4 (57.9)
3                   13.4 (56.1)                   8.3 (46.9)
4                    0.1 (32.2)                 −11.2 (11.8)
5                       5 (0.2)                     24 (0.9)
6                         0 (0)                        0 (0)
7                             3                            7
8                             0                            1
9                            45                           57
10                        283.8                        220.4
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]

                                                              \
                            Nov                          Dec
0                   31.6 (88.9)                  27.3 (81.1)
1                   14.1 (57.4)                   8.6 (47.5)
2                    8.1 (46.6)                   3.5 (38.3)
3                    3.6 (38.5)                  −0.1 (31.8)
4                  −22.1 (−7.8)                −29.5 (−21.1)
5                      51 (2.0)                     58 (2.3)
6                         0 (0)                      2 (0.8)
7                            10                           12
8                             2                            6
9                            66                           73
10                        135.0                        104.7
11  Source 1: Pogoda.ru.net[54]  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]           Source 2: NOAA[55]


                           Year
0                  44.6 (112.3)
1                   21.8 (71.3)
2                   15.2 (59.3)
3                    9.2 (48.6)
4                 −29.5 (−21.1)
5                      457 (18)
6                       3 (1.2)
7                           110
8                            27
9                            56
10                       2755.6
11  Source 1: Pogoda.ru.net[54]
12           Source 2: NOAA[55]

In [49]:
tashkent[6]

,0,1,2
0,"YearPop.±% p.a.1897 155,673— 1959 911,930+2.89...","YearPop.±% p.a.2007 2,157,100+0.77%2008 2,180,...",NaN
1,Year,Pop.,±% p.a.
2,1897,155673,—
3,1959,911930,+2.89%
4,1970,1384509,+3.87%
5,1979,1780002,+2.83%
6,1983,1902000,+1.67%
7,1989,2072459,+1.44%
8,1991,2130200,+1.38%
9,1995,2097400,−0.39%
10,2000,2142300,+0.42%
11,2001,2137900,−0.21%
12,2002,2136600,−0.06%
13,2003,2139200,+0.12%
14,2004,2135400,−0.18%
15,2005,2135700,+0.01%
16,2006,2140600,+0.23%
17,Year,Pop.,±% p.a.
18,2007,2157100,+0.77%
19,2008,2180000,+1.06%
20,2009,2206300,+1.21%
21,2010,2234300,+1.27%
22,2011,2296500,+2.78%
23,2012,2309300,+0.56%
24,2013,2340900,+1.37%
25,2014,2352900,+0.51%
26,2015,2371300,+0.78%
27,2016,2393200,+0.92%
28,2017,2424100,+1.29%
29,2018,2464900,+1.68%
30,2019,2509900,+1.83%
31,2020,2571700,+2.46%
32,2021,2694400,+4.77%
33,Graphs are unavailable due to technical issues...,Graphs are unavailable due to technical issues...,NaN
34,NaN,Graphs are unavailable due to technical issues...,NaN
35,Source: Uzbekistan State Statistics Committee[...,Source: Uzbekistan State Statistics Committee[...,NaN

In [ ]:
# JSON formatidagi jadvallarni ochish va o'qish
# JSON eng mashhur format hisoblanadi
pd.read_json("")