<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/NumPy-and-Pandas/Ma%CA%BClumotlarni_filtrlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/merc.csv')
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0
...,...,...,...,...,...,...,...,...,...
13114,C Class,2020,35999,Automatic,500,Diesel,145,55.4,2.0
13115,B Class,2020,24699,Automatic,2500,Diesel,145,55.4,2.0
13116,GLC Class,2019,30999,Automatic,11612,Diesel,145,41.5,2.1
13117,CLS Class,2019,37990,Automatic,2426,Diesel,145,45.6,2.0
13118,S Class,2019,54999,Automatic,2075,Diesel,145,52.3,2.9

In [8]:
# biz takrorlangan elementlarni filter qilishimiz kerak
# model variable ichidagi takrorlanmas elementlar
model = df["model"].unique()
model.sort()
model

array([' A Class', ' B Class', ' C Class', ' CL Class', ' CLA Class',
       ' CLC Class', ' CLK', ' CLS Class', ' E Class', ' G Class',
       ' GL Class', ' GLA Class', ' GLB Class', ' GLC Class',
       ' GLE Class', ' GLS Class', ' M Class', ' R Class', ' S Class',
       ' SL CLASS', ' SLK', ' V Class', ' X-CLASS', '180', '200', '220',
       '230'], dtype=object)

In [4]:
# transmission variable ichidagi takrorlanmas elementlar
df["transmission"].unique()

array(['Automatic', 'Manual', 'Semi-Auto', 'Other'], dtype=object)

In [9]:
# model ichidagi elementlarning har biriga tegishli bo'lgan qaytarilgan soni hisoblaydi
df["model"].value_counts()

model
 C Class      3747
 A Class      2561
 E Class      1953
 GLC Class     960
 GLA Class     847
 B Class       591
 CL Class      511
 GLE Class     461
 SL CLASS      260
 CLS Class     237
 V Class       207
 S Class       197
 GL Class      121
 SLK            95
 CLA Class      86
 X-CLASS        82
 M Class        79
 GLS Class      74
 GLB Class      19
 G Class        15
 CLK             7
 CLC Class       3
 R Class         2
180              1
230              1
220              1
200              1
Name: count, dtype: int64

In [10]:
df["transmission"].unique()
df["transmission"].value_counts()

transmission
Semi-Auto    6848
Automatic    4825
Manual       1444
Other           2
Name: count, dtype: int64

In [11]:
# bizga model ichidagi ' CLK', ' CLS Class' ma'lumotlar kerak
class_c = df["model"].isin([' CLK', ' CLS Class'])
class_c

0        False
1        False
2        False
3        False
4        False
         ...
13114    False
13115    False
13116    False
13117     True
13118    False
Name: model, Length: 13119, dtype: bool

In [13]:
#' CLK', ' CLS Class' lar dataframe yaratildi
df[class_c]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
26,CLS Class,2016,25077,Automatic,13887,Diesel,165,49.6,3.0
41,CLS Class,2018,34990,Automatic,18837,Diesel,150,47.9,2.9
97,CLS Class,2017,26166,Automatic,9165,Diesel,150,51.4,3.0
110,CLS Class,2019,37352,Automatic,3000,Diesel,150,45.6,2.0
163,CLS Class,2014,15998,Semi-Auto,31815,Diesel,145,54.3,2.1
...,...,...,...,...,...,...,...,...,...
12985,CLS Class,2016,22421,Automatic,26236,Diesel,165,51.4,3.0
13057,CLS Class,2016,17999,Automatic,47156,Diesel,125,57.7,2.1
13085,CLS Class,2016,22684,Automatic,32611,Diesel,165,49.6,3.0
13095,CLS Class,2016,20399,Automatic,16107,Diesel,160,51.4,3.0
13117,CLS Class,2019,37990,Automatic,2426,Diesel,145,45.6,2.0

In [14]:
df[(df.price > 20000) & (df.year < 2010)]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
12072,M Class,1970,24999,Automatic,14000,Diesel,305,39.2,0.0

In [15]:
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0
...,...,...,...,...,...,...,...,...,...
13114,C Class,2020,35999,Automatic,500,Diesel,145,55.4,2.0
13115,B Class,2020,24699,Automatic,2500,Diesel,145,55.4,2.0
13116,GLC Class,2019,30999,Automatic,11612,Diesel,145,41.5,2.1
13117,CLS Class,2019,37990,Automatic,2426,Diesel,145,45.6,2.0
13118,S Class,2019,54999,Automatic,2075,Diesel,145,52.3,2.9

In [16]:
df[df.transmission == "Manual"]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
34,A Class,2019,23184,Manual,1173,Petrol,145,44.8,1.3
56,A Class,2011,3440,Manual,74000,Diesel,150,54.3,2.0
61,E Class,2010,6980,Manual,79000,Petrol,300,35.3,1.8
63,E Class,2011,5740,Manual,115000,Diesel,160,52.3,2.1
81,SLK,2010,7495,Manual,59147,Petrol,300,36.2,1.8
...,...,...,...,...,...,...,...,...,...
13011,V Class,2013,20000,Manual,58518,Diesel,305,38.7,2.1
13014,B Class,2017,13950,Manual,5878,Diesel,20,68.9,1.5
13015,GLA Class,2017,17000,Manual,26000,Petrol,145,48.7,1.6
13024,A Class,2016,16500,Manual,16984,Diesel,30,62.8,2.1
13034,A Class,2017,13391,Manual,38172,Diesel,145,72.4,1.5