<a href="https://colab.research.google.com/github/AbdullahTheAnalyst/Data-Science-and-AI-mohir_dev-/blob/NumPy-and-Pandas/Multi_indexlash_(pivot_table).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

Multi indexlash

Hierarchial indexing

Bir nechta indexdan tashkil topgan

In [3]:
# bu Multi indexlash bizga juda katta database ga ishlov berish uchun kerak bo'ladi
# Odatiy Series to'plam
data = pd.Series(np.random.randn(9), index = ["a",
                                              "a",
                                              "a",
                                              "b",
                                              "b",
                                              "c",
                                              "c",
                                              "d",
                                              "d",
                                              ])
data

a   -0.613988
a    0.211252
a    0.679121
b   -0.920841
b    0.809722
c    0.045719
c   -2.279668
d   -0.033651
d    0.592091
dtype: float64

In [4]:
data.index

Index(['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'], dtype='object')

In [8]:
# buni multi - indexga alishtiramiz
# yuqori masshtabli db uchun guruhlashga juda yordam beradi
data1 = pd.Series(np.random.randn(9), index = [["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                                              [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data1

a  1    0.574189
   2   -0.621947
   3   -0.106826
b  1    2.203508
   3    0.634226
c  1    0.305561
   2    0.666470
d  2   -0.511441
   3   -1.330479
dtype: float64

In [9]:
data1.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [11]:
# faqat c indexiga tegishli datani ajratib olamiz
data1["c"]

1    0.305561
2    0.666470
dtype: float64

In [12]:
# ko'p indexini ajratib olish
data1["c" : "d"]

c  1    0.305561
   2    0.666470
d  2   -0.511441
   3   -1.330479
dtype: float64

In [13]:
data1["a" : "c"]

a  1    0.574189
   2   -0.621947
   3   -0.106826
b  1    2.203508
   3    0.634226
c  1    0.305561
   2    0.666470
dtype: float64

In [14]:
# barcha 3-indexga tegishli elementlarni ajratib olish
data1.loc[ : , 3]

a   -0.106826
b    0.634226
d   -1.330479
dtype: float64

In [15]:
# barcha b va c indexdagi elementlar
data1.loc[["b", "c"]]

b  1    2.203508
   3    0.634226
c  1    0.305561
   2    0.666470
dtype: float64

In [17]:
# unstack va stack usullari juda foydali hisoblanadi
# unstack -> bu multi-indexdan dataframega sochib yuboradi
# unstack -> sochilgan Seriesni df ko'rinishiga qaytaradi
data1.unstack()

          1         2         3
a  0.574189 -0.621947 -0.106826
b  2.203508       NaN  0.634226
c  0.305561  0.666470       NaN
d       NaN -0.511441 -1.330479

In [18]:
# stack -> df.ni yig'ilgan Series.ga o'giradi
data1.unstack().stack()

a  1    0.574189
   2   -0.621947
   3   -0.106826
b  1    2.203508
   3    0.634226
c  1    0.305561
   2    0.666470
d  2   -0.511441
   3   -1.330479
dtype: float64

Dunyo shaharlarining havo va suv sifati to'g'risida dataset

In [20]:
# git hubdan repository.ni yuklab olish
! git clone https://github.com/MansurCompAI/Practicum_Datasets.git

fatal: destination path 'Practicum_Datasets' already exists and is not an empty directory.

In [22]:
df = pd.read_csv("/content/Practicum_Datasets/world_cities_air_water_quality.csv")
df.head()

,City,"""Region""","""Country""","""AirQuality""","""WaterPollution"""
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435

In [23]:
# har doim data cleaning.dan oldin albatta data haqida ma'lumotlari haqida info ol
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3963 entries, 0 to 3962
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               3963 non-null   object
 1    "Region"          3963 non-null   object
 2    "Country"         3963 non-null   object
 3    "AirQuality"      3963 non-null   float64
 4    "WaterPollution"  3963 non-null   float64
dtypes: float64(2), object(3)
memory usage: 154.9+ KB

In [26]:
# ishni column name.ni to'g'irlashdan boshlaymiz ("" ichida yozilgan xatosi)
index_col = ["City", "Region", "Country", "AirQuality", "WaterPollution"]
df.columns = index_col
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,"""New York""","""United States of America""",46.816038,49.504950
1,"Washington, D.C.","""District of Columbia""","""United States of America""",66.129032,49.107143
2,San Francisco,"""California""","""United States of America""",60.514019,43.000000
3,Berlin,"""""","""Germany""",62.364130,28.612717
4,Los Angeles,"""California""","""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,"""Medina Province""","""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,"""Andalusia""","""Spain""",85.714286,8.333333
3960,Vic,"""Catalonia""","""Spain""",100.000000,0.000000
3961,Segovia,"""Castile and Leon""","""Spain""",100.000000,0.000000
3962,Zamora city,"""Castile and Leon""","""Spain""",100.000000,50.000000

In [27]:
# Region va Country ichida hamma element "" ichida yozilgan va buni to'g'irlashimiz kerak
# .map(lambda x: x.replace('"', '')) -> " ning o'rnida bo'sh qoldirish uchun dastur
df["Region"] = df["Region"].map(lambda x: x.replace('"', ''))
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,"""United States of America""",46.816038,49.504950
1,"Washington, D.C.",District of Columbia,"""United States of America""",66.129032,49.107143
2,San Francisco,California,"""United States of America""",60.514019,43.000000
3,Berlin,,"""Germany""",62.364130,28.612717
4,Los Angeles,California,"""United States of America""",36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,"""Saudi Arabia""",0.000000,50.000000
3959,Cordoba,Andalusia,"""Spain""",85.714286,8.333333
3960,Vic,Catalonia,"""Spain""",100.000000,0.000000
3961,Segovia,Castile and Leon,"""Spain""",100.000000,0.000000
3962,Zamora city,Castile and Leon,"""Spain""",100.000000,50.000000

In [28]:
# Region va Country ichida hamma element "" ichida yozilgan va buni to'g'irlashimiz kerak
# .map(lambda x: x.replace('"', '')) -> " ning o'rnida bo'sh qoldirish uchun dastur
df["Country"] = df["Country"].map(lambda x: x.replace('"', ''))
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [30]:
# yuqorida update qilingan data.ni yangi csv file.ga save qilish kerak
# index = False ->boshqa index paydo bo'lishini oldini oladi
df.to_csv("Updated_dataset", index = False)

In [31]:
# bui bajarsak, Germany oldida space mavjudligini ko'rishimiz mumkin
df[df["Country"] == "Germany"]

Empty DataFrame
Columns: [City, Region, Country, AirQuality, WaterPollution]
Index: []

In [33]:
df["Country"][100]

' India'

In [34]:
df["Country"] = df["Country"].map(lambda x: x.strip())
df

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000
3,Berlin,,Germany,62.364130,28.612717
4,Los Angeles,California,United States of America,36.621622,61.299435
...,...,...,...,...,...
3958,Yanbu,Medina Province,Saudi Arabia,0.000000,50.000000
3959,Cordoba,Andalusia,Spain,85.714286,8.333333
3960,Vic,Catalonia,Spain,100.000000,0.000000
3961,Segovia,Castile and Leon,Spain,100.000000,0.000000
3962,Zamora city,Castile and Leon,Spain,100.000000,50.000000

In [35]:
df["Country"][100]

'India'

In [37]:
# germany.ga tegishli data.lar chiqardik
df[df["Country"] == "Germany"]

,City,Region,Country,AirQuality,WaterPollution
3,Berlin,,Germany,62.364130,28.612717
28,Cologne,North Rhine-Westphalia,Germany,60.714286,27.777778
40,Bonn,North Rhine-Westphalia,Germany,82.812500,22.500000
52,Heilbronn,Baden-Wurttemberg,Germany,80.000000,0.000000
76,Aachen,North Rhine-Westphalia,Germany,70.454545,17.857143
...,...,...,...,...,...
2693,Bad Waldsee,Baden-Wurttemberg,Germany,100.000000,50.000000
2714,Weilheim in Oberbayern,Bavaria,Germany,100.000000,50.000000
2727,Buckow,Brandenburg,Germany,87.500000,50.000000
3942,Erfurt,Thuringia,Germany,85.000000,50.000000
3943,Garmisch-Partenkirchen,Bavaria,Germany,100.000000,50.000000

In [38]:
# uzbekistanga.ga tegishli data.lar chiqardik
df[df["Country"] == "Uzbekistan"]

        City Region     Country  AirQuality  WaterPollution
21  Tashkent         Uzbekistan   56.451613       49.166667

**pivot_table** orqali multi-indexlash

In [40]:
df.head(3)

,City,Region,Country,AirQuality,WaterPollution
0,New York City,New York,United States of America,46.816038,49.504950
1,"Washington, D.C.",District of Columbia,United States of America,66.129032,49.107143
2,San Francisco,California,United States of America,60.514019,43.000000

In [42]:
# qiymatlati 'AirQuality', 'WaterPollution' bo'lgan pivot table
df1 = pd.pivot_table(df, index = ["Country", "City"], values=['AirQuality', 'WaterPollution'])

In [43]:
df1

                      AirQuality  WaterPollution
Country     City
Afghanistan Andkhoy    50.000000       50.000000
            Farah     100.000000        0.000000
            Herat      43.750000       31.250000
            Kabul      18.421053       81.060606
            Kandahar    0.000000       75.000000
...                          ...             ...
Zambia      Mansa      75.000000       25.000000
Zimbabwe    Bindura    50.000000       75.000000
            Bulawayo   67.857143       71.428571
            Harare     38.461538       87.500000
            Masvingo   25.000000       62.500000

[3895 rows x 2 columns]

In [44]:
df1.index

MultiIndex([('Afghanistan',        'Andkhoy'),
            ('Afghanistan',          'Farah'),
            ('Afghanistan',          'Herat'),
            ('Afghanistan',          'Kabul'),
            ('Afghanistan',       'Kandahar'),
            ('Afghanistan', 'Mazar-i-Sharif'),
            (    'Albania',         'Ballsh'),
            (    'Albania',         'Burrel'),
            (    'Albania',         'Durres'),
            (    'Albania',        'Elbasan'),
            ...
            (      'Yemen',          'Sanaa'),
            (      'Yemen',         'Ta'izz'),
            (     'Zambia',       'Chingola'),
            (     'Zambia',          'Kitwe'),
            (     'Zambia',         'Lusaka'),
            (     'Zambia',          'Mansa'),
            (   'Zimbabwe',        'Bindura'),
            (   'Zimbabwe',       'Bulawayo'),
            (   'Zimbabwe',         'Harare'),
            (   'Zimbabwe',       'Masvingo')],
           names=['Country', 'City'], length=3895)

In [45]:
df1.loc[["Uzbekistan", "Tajikistan", "Zambia"]]

                     AirQuality  WaterPollution
Country    City
Uzbekistan Tashkent   56.451613       49.166667
Tajikistan Dushanbe   41.666667       61.111111
Zambia     Chingola   75.000000      100.000000
           Kitwe       0.000000      100.000000
           Lusaka     33.333333       98.076923
           Mansa      75.000000       25.000000